stages:
  - build
  - deploy

default:
  before_script:
    - echo $CI_REGISTRY
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

services:
  - docker:stable-dind

build-server:
  stage: build
  image: docker:stable
  script:
    - docker build -t $CI_REGISTRY_IMAGE/sibumi-server:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE/sibumi-server:latest server
    - docker push $CI_REGISTRY_IMAGE/sibumi-server:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/sibumi-server:latest

build-client:
  stage: build
  image: docker:stable
  script:
    - docker build -t $CI_REGISTRY_IMAGE/sibumi-client:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE/sibumi-client:latest client
    - docker push $CI_REGISTRY_IMAGE/sibumi-client:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/sibumi-client:latest


deploy-job:
  stage: deploy
  tags: [docker-production]
  environment: production
  script:
    - cp $DB_ENV_PATH ./
    - cp $SERVER_ENV_PATH ./server/
    - docker pull $CI_REGISTRY_IMAGE/sibumi-client:latest
    - docker pull $CI_REGISTRY_IMAGE/sibumi-server:latest
    - docker compose -f docker-compose.yml -f production.yml up -d --no-build
