version: "3.9"

services:

  postgres:
    env_file:
      ./container.env
      
  server:
    env_file:
      - ./server/.env
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.backend.rule=Host(`localhost`) && PathPrefix(`/api`)"
    - "traefik.http.routers.backend.entrypoints=web"
    - "traefik.http.routers.backend.middlewares=strip-api"
    - "traefik.http.middlewares.strip-api.stripprefix.prefixes=/api"
  
  client:
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.client.rule=Host(`localhost`)"
    - "traefik.http.routers.client-backend.entrypoints=web"

  traefik:
    ports:
      - 3000:80
    volumes:
      - ${SOCK_PATH:-/var/run/docker.sock}:/var/run/docker.sock:ro
  
